import = ["~/.config/alacritty/themes/themes/ashes_dark.toml"]

[font]
size = 14.0
normal.family = "MesloLGS Nerd Font Mono"

[window]
opacity = 0.93
blur = true

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]
